### ISSUE TITLE
The AI Review job had been stuck with starting rails server. No comments added

### ISSUE THREAD

**Issue by indyarocks** [freeedcom/ai-codereviewer#104]
No code review generated.

.github/workflows/main.yml
```
name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Replace with your Rails app's Ruby version

      - name: Install Dependencies
        run: |
          bundle install
          yarn install --check-files

      - name: Configure Rails Secret Key
        run: echo "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}" >> $GITHUB_ENV

      - name: Ensure Writable Directories
        run: |
          mkdir -p tmp/sockets tmp/pids log storage
          chmod -R 777 tmp log storage

      - name: Prepare Database
        run: bin/rails db:create db:migrate RAILS_ENV=test

      - name: Run AI Code Reviewer
        uses: indyarocks/hackathon_dec2024@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas

```

<img width="1293" alt="Screenshot 2024-12-09 at 6 17 58 PM" src="https://github.com/user-attachments/assets/7a32413c-34bf-4dec-aa40-ce5f5a3c1513">
