### ISSUE TITLE
Not Found 404 

### ISSUE THREAD

**Issue by DanielBelz1997** [freeedcom/ai-codereviewer#105]
i forked the ai-codereviewer repo, but the workflow fails:
log:
```
Run DanielBelz1997/ai-codereviewer@main
Error: RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/DanielBelz199[7](https://github.com/DanielBelz1997/project_manager_frontend/actions/runs/12251642548/job/34176668105#step:3:8)/ai-codereviewer/main/webpack:/open-ai-reviewer/node_modules/@octokit/request/dist-node/index.js:7[8](https://github.com/DanielBelz1997/project_manager_frontend/actions/runs/12251642548/job/34176668105#step:3:9):1
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/DanielBelz1[9](https://github.com/DanielBelz1997/project_manager_frontend/actions/runs/12251642548/job/34176668105#step:3:10)97/project_manager_frontend/pulls/',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, [10](https://github.com/DanielBelz1997/project_manager_frontend/actions/runs/12251642548/job/34176668105#step:3:11) Dec 2024 07:49:14 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-[11](https://github.com/DanielBelz1997/project_manager_frontend/actions/runs/12251642548/job/34176668105#step:3:12)-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '9081:3B750D:E2A5AD:1C0E1BD:6757F279',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4997',
      'x-ratelimit-reset': '1733817675',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '3',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest',
      status: '404'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/DanielBelz1997/project_manager_frontend/pulls/',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.7 octokit-core.js/4.2.0 Node.js/20.18.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

the yml file: 

```
name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "feature/*" # Replace with the branch pattern you want to trigger on
      - "hotfix/*" # Example: Matches branches like 'feature/my-feature' or 'hotfix/urgent-fix'

permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: DanielBelz1997/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
```
