### ISSUE TITLE
Error: NotFoundError: 404 The model `gpt-4` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by HumanBot000** [freeedcom/ai-codereviewer#124]
```yml
name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: aidar-freeed/ai-codereviewer@v2.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" 
```
