### ISSUE TITLE
Workflow failed

### ISSUE THREAD

**Issue by maxbaluev** [freeedcom/ai-codereviewer#21]
Codereviewer workflow failed with urgent error

My config:
```
name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: Inside-AI-me/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
```

[Full log](https://gist.github.com/maxbaluev/83549180b1653488ed24945a63165aaa)
