### ISSUE TITLE
Workflow Fails [Resource not accessible by personal access token]

### ISSUE THREAD

**Issue by arshharkial** [freeedcom/ai-codereviewer#24]
```yaml
name: AI Code Reviewer

on:
  pull_request:
    types:
    - opened
    - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: AI Code Reviewer
      uses: freeedcom/ai-codereviewer@v2.6.0
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
        exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
```
![image](https://github.com/freeedcom/ai-codereviewer/assets/40192673/190f0261-0000-4aea-bf1e-508ec44a79a5)
